global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@watermark-lab.com'
  smtp_auth_username: 'alerts@watermark-lab.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m
    - match:
        severity: warning
      receiver: 'warning-alerts'
      repeat_interval: 2h
    - match:
        service: security
      receiver: 'security-alerts'
      group_wait: 0s
      repeat_interval: 15m

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://localhost:8080/api/v1/alerts/webhook'
        send_resolved: true

  - name: 'critical-alerts'
    email_configs:
      - to: 'admin@watermark-lab.com'
        subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt }}
          {{ if .EndsAt }}**Ended:** {{ .EndsAt }}{{ end }}
          
          **Labels:**
          {{ range .Labels.SortedPairs }}
          - {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    
    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-critical'
        title: '🚨 Critical Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          {{ .Annotations.description }}
          
          *Service:* {{ .Labels.service }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
        color: 'danger'
        send_resolved: true

    pagerduty_configs:
      - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
        description: '{{ .GroupLabels.alertname }}: {{ .GroupLabels.service }}'

  - name: 'warning-alerts'
    email_configs:
      - to: 'team@watermark-lab.com'
        subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt }}
          {{ if .EndsAt }}**Ended:** {{ .EndsAt }}{{ end }}
          {{ end }}

    slack_configs:
      - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        channel: '#alerts-warning'
        title: '⚠️ Warning: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          {{ .Annotations.description }}
          
          *Service:* {{ .Labels.service }}
          {{ end }}
        color: 'warning'
        send_resolved: true

  - name: 'security-alerts'
    email_configs:
      - to: 'security@watermark-lab.com'
        subject: '🔒 SECURITY ALERT: {{ .GroupLabels.alertname }}'
        body: |
          **SECURITY ALERT DETECTED**
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Severity:** {{ .Labels.severity }}
          **Started:** {{ .StartsAt }}
          
          **Immediate Action Required**
          Please investigate this security incident immediately.
          
          **Labels:**
          {{ range .Labels.SortedPairs }}
          - {{ .Name }}: {{ .Value }}
          {{ end }}
          {{ end }}

    slack_configs:
      - api_url: 'YOUR_SECURITY_SLACK_WEBHOOK_URL'
        channel: '#security-alerts'
        title: '🔒 SECURITY ALERT: {{ .GroupLabels.alertname }}'
        text: |
          <!channel> **SECURITY ALERT**
          
          {{ range .Alerts }}
          **{{ .Annotations.summary }}**
          {{ .Annotations.description }}
          
          *Immediate investigation required*
          {{ end }}
        color: 'danger'
        send_resolved: true

    webhook_configs:
      - url: 'http://localhost:8080/api/v1/security/alerts'
        send_resolved: true
        http_config:
          basic_auth:
            username: 'alert-webhook'
            password: 'your-webhook-password'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'service', 'instance']

  - source_match:
      alertname: 'APIDown'
    target_match_re:
      alertname: 'API.*'
    equal: ['service', 'instance']