name: Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide details below to help us understand your request.

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see added.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: Describe the problem this feature would solve...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you envision this feature working?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: Which area does this feature relate to?
      options:
        - Watermarking Algorithms
        - Detection Methods
        - Attack Techniques
        - Evaluation Metrics
        - API/CLI Interface
        - Visualization
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...
    validations:
      required: false

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: |
        If applicable, provide a code example of how you'd like to use this feature.
        This will be formatted as Python code.
      render: python
      placeholder: |
        # Example of how the feature might be used
        from watermark_lab import NewFeature
        
        feature = NewFeature()
        result = feature.do_something()
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you willing to help implement this feature?
      options:
        - label: I would be willing to implement this feature myself
          required: false
        - label: I would be willing to help test this feature
          required: false
        - label: I would be willing to help document this feature
          required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests that may be the same as this one
          required: true
        - label: I have provided a clear and concise description of the feature
          required: true
        - label: I have explained the problem this feature would solve
          required: true