name: Security Report
description: Report a security vulnerability (private)
title: "[SECURITY] "
labels: ["security", "needs-triage"]
assignees: ["@terragon-labs/security-team"]

body:
  - type: markdown
    attributes:
      value: |
        **⚠️ SECURITY NOTICE ⚠️**
        
        If you believe you have found a security vulnerability, please DO NOT create a public issue.
        Instead, please email us at security@terragonlabs.com with details.
        
        For non-sensitive security improvements or questions, you may use this template.

  - type: dropdown
    id: security-type
    attributes:
      label: Security Issue Type
      description: What type of security issue is this?
      options:
        - Security Enhancement Request
        - Security Documentation Issue
        - Security Tool Configuration
        - General Security Question
        - Other (Not a Vulnerability)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security improvement or question
      placeholder: Describe the security issue...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this should be addressed?
      placeholder: Describe your proposed solution...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the security issue
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: This is NOT a vulnerability report (vulnerabilities should be emailed to security@terragonlabs.com)
          required: true
        - label: I understand this issue will be publicly visible
          required: true